[package]
name = "iloader"
version = "0.1.0"
edition = "2021"

[dependencies]
rusb = "0.9.4"
regex = "1.11.1"
iced = { version = "0.13.1", features = ["tokio", "svg", "markdown", "highlighter", "system", "web-colors", "debug"] }
iced_font_awesome = "0.2.0"